const { client } = require("./client.js");
const express = require("express");
const app = express();

async function createTablesAndData() {
  try {
    const SQL = `
        DROP TABLE IF EXISTS comments;
        DROP TABLE IF EXISTS reviews;
        DROP TABLE IF EXISTS users;
        DROP TABLE IF EXISTS albums;

        CREATE TABLE albums (
          id SERIAL PRIMARY KEY,
          name varchar(255) UNIQUE NOT NULL,
          artistName varchar(255) NOT NULL,
          releaseYear INTEGER,
          song1 varchar(255),
          song2 varchar(255),
          song3 varchar(255),
          song4 varchar(255),
          song5 varchar(255),
          song6 varchar(255),
          song7 varchar(255),
          song8 varchar(255),
          song9 varchar(255),
          song10 varchar(255),
          song11 varchar(255),
          song12 varchar(255),
          song13 varchar(255),
          song14 varchar(255),
          song15 varchar(255),
          genre varchar(255) NOT NULL,
          albumArt TEXT,
          spotifyLink TEXT
        );

        CREATE TABLE users (
          id SERIAL PRIMARY KEY,
          username varchar(255) UNIQUE NOT NULL,
          password varchar(255) NOT NULL,
          active boolean DEFAULT true
        );

        CREATE TABLE reviews (
          id SERIAL PRIMARY KEY,
          "userId" INTEGER REFERENCES users(id),
          content TEXT NOT NULL,
          rating INTEGER,
          active BOOLEAN DEFAULT true
        );

        CREATE TABLE comments (
          id SERIAL PRIMARY KEY,
          "reviewId" INTEGER REFERENCES reviews(id),
          content TEXT NOT NULL,
          active BOOLEAN DEFAULT true
        );

        INSERT INTO albums (
          name,
          artistName,
          releaseYear,
          song1,
          song2,
          song3,
          song4,
          song5,
          song6,
          song7,
          song8,
          song9,
          song10,
          song11,
          song12,
          song13,
          song14,
          song15,
          genre,
          albumArt,
          spotifyLink
          )

        VALUES

        (
        'Future Nostalgia',
        'Dua Lipa',
        '2020',
        'Future Nostalgia',
        'Dont Start Now',
        'Cool',
        'Physical',
        'Levitating',
        'Pretty Please',
        'Hallucinate', 
        'Love Again',
        'Break My Heart',
        'Good in Bed',
        'Boys Will Be Boys',
        '',
        '',
        '',
        '',
        'Pop',
        'futurenostalgia.jpg',
        'https://open.spotify.com/album/7fJJK56U9fHixgO0HQkhtI'
        ),

        (
        'Folklore',
        'Taylor Swift',
        '2020',
        'the 1',
        'cardigan',
        'the last great american dynasty',
        'exile (feat. Bon Iver)',
        'my tears ricochet',
        'mirrorball',
        'seven',
        'august',
        'this is me trying',
        'illicit affairs',
        'invisible string',
        'mad woman',
        'epiphany',
        'betty',
        'peace',
        'Folk',
        'folklore.png',
        'https://open.spotify.com/album/1pzvBxYgT6OVwJLtHkrdQK'
        ),

        (
        'DAMN.',
        'Kendrick Lamar',
        '2017',
        'BLOOD.',
        'DNA.',
        'YAH.',
        'ELEMENT.',
        'FEEL.',
        'LOYALTY. (feat. Rihanna)',
        'PRIDE.',
        'HUMBLE.',
        'LUST.',
        'LOVE. (feat. Zacari)',
        'XXX. (feat. U2)',
        'FEAR.',
        'GOD.',
        'DUCKWORTH.',
        '',
        'Hip-Hop',
        'damn.jpeg',
        'https://open.spotify.com/album/4eLPsYPBmXABThSJ821sqY'
        ),

        (
        'Lover',
        'Taylor Swift',
        '2019',
        'I Forgot That You Existed',
        'Cruel Summer',
        'Lover',
        'The Man',
        'The Archer',
        'I Think He Knows',
        'Miss Americana & The Heartbreak Prince',
        'Paper Rings',
        'Cornelia Street',
        'Death by a Thousand Cuts',
        'London Boy',
        'Soon Youll Get Better',
        'False God',
        'You Need to Calm Down',
        'Daylight',
        'Pop',
        'lover.png',
        'https://open.spotify.com/track/1dGr1c8CrMLDpV6mPbImSI'
        ),

        (
        'Blinding Lights',
        'The Weeknd',
        '2020',
        'Blinding Lights',
        'Heartless',
        'Save Your Tears',
        'In Your Eyes',
        'After Hours',
        'Alone Again',
        'Hardest To Love',
        'Scared To Live',
        'Snowchild',
        'Escape From LA',
        'Pray For Me',
        'Faith',
        '',
        '',
        '',
        'R&B',
        'blindinglights.png',
        'https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b'
        ),

        (
        'When We All Fall Asleep, Where Do We Go?',
        'Billie Eilish',
        '2019',
        '!!!!!!!',
        'bad guy',
        'xanny',
        'you should see me in a crown',
        'all the good girls go to hell',
        'wish you were gay',
        'when the partys over',
        '8',
        'my strange addiction',
        'bury a friend',
        'ilomilo',
        'listen before i go',
        'i love you',
        'goodbye',
        'everything i wanted',
        'Alternative',
        'whenweallfallasleep.png',
        'https://open.spotify.com/album/0S0KGZnfBGSIssfF54WSJh'
        ),

        (
        'Happier Than Ever',
        'Billie Eilish',
        '2021',
        'Getting Older',
        'I Didnt Change My Number',
        'Billie Bossa Nova',
        'My Future',
        'Oxytocin',
        'Goldwing',
        'Lost Cause',
        'Halleys Comet',
        'Not My Responsibility',
        'Overheated',
        'Everybody Dies',
        'Your Power',
        'NDA',
        'Therefore I Am',
        'Happier Than Ever',
        'Pop',
        'happierthanever.png',
        'https://open.spotify.com/track/4RVwu0g32PAqgUiJoXsdF8'
        ),

        (
        'Hot Pink',
        'Doja Cat',
        '2019',
        'Cyber Sex',
        'Like That',
        'Juicy',
        'Say So',
        'Mooo!',
        'Tia Tamera',
        'Streets',
        'Bottom Bitch',
        'Better Than Me',
        'Talk Dirty',
        'Lick',
        'Candy',
        'No Drama',
        'Rules',
        'Love To Dream',
        'Pop',
        'hotpink.jpg',
        'https://open.spotify.com/playlist/37i9dQZF1DX45grRWk2ghU'
        ),

        (
        'In the Aeroplane Over the Sea', 
        'Neutral Milk Hotel', 
        '1998', 
        'The King of Carrot Flowers Pt. One', 
        'The King of Carrot Flowers Pt. Two & Three', 
        'In the Aeroplane Over the Sea', 
        'Two-Headed Boy', 
        'The Fool', 
        'Holland, 1945', 
        'Communist Daughter', 
        'Oh Comely', 
        'Ghost', 
        'Untitled', 
        'The King of Carrot Flowers Pt. One',
        '',
        '',
        '',
        '',
        'Indie Rock',
        'aeroplane.jpg',
        'https://open.spotify.com/track/5rfT032kGmLvbxZzfHlu5D'
        ),

        (
        'Random Access Memories', 
        'Daft Punk', 
        '2013', 
        'Give Life Back to Music', 
        'The Game of Love', 
        'Giorgio by Moroder', 
        'Within', 
        'Instant Crush', 
        'Lose Yourself to Dance', 
        'Touch', 
        'Get Lucky', 
        'Beyond', 
        'Motherboard',
        '',
        '',
        '',
        '',
        '',
        'Electronic',
        'ram.png',
        'https://open.spotify.com/album/4m2880jivSbbyEGAKfITCa'
        ),

        (
        'To Pimp a Butterfly', 
        'Kendrick Lamar', 
        '2015', 
        'Wesleys Theory', 
        'For Free? (Interlude)', 
        'King Kunta', 
        'Institutionalized', 
        'These Walls', 
        'u', 
        'Alright', 
        'For Sale? (Interlude)', 
        'Momma', 
        'Hood Politics', 
        '',
        '',
        '',
        '',
        '',
        'Hip-Hop',
        'butterfly.png',
        'https://open.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP'
        ),

        (
        'Channel Orange', 
        'Frank Ocean', 
        '2012', 
        'Start', 
        'Thinkin Bout You', 
        'Fertilizer', 
        'Sierra Leone', 
        'Sweet Life', 
        'Not Just Money', 
        'Super Rich Kids', 
        'Pilot Jones', 
        'Crack Rock', 
        'Pyramids',
        '',
        '',
        '',
        '',
        '',
        'R&B',
        'channelorange.jpg',
        'https://open.spotify.com/album/392p3shh2jkxUxY2VHvlH8'
         ),

         (
        'AM', 
        'Arctic Monkeys', 
        '2013', 
        'Do I Wanna Know?', 
        'R U Mine?', 
        'One for the Road', 
        'Arabella', 
        'I Wanna Be Yours', 
        'No. 1 Party Anthem', 
        'Mad Sounds', 
        'Fireside', 
        'Whyd You Only Call Me When Youre High?',
        '',
        '',
        '',
        '',
        '',
        '',
        'Indie Rock',
        'am.jpg',
        'https://open.spotify.com/album/78bpIziExqiI9qztvNFlQu'
        ),

(
    'My Beautiful Dark Twisted Fantasy', 
    'Kanye West', 
    '2010', 
    'Dark Fantasy', 
    'Gorgeous', 
    'Power', 
    'All of the Lights', 
    'Monster', 
    'So Appalled', 
    'Devil in a New Dress', 
    'Runaway', 
    'Hell of a Life', 
     '',
        '',
        '',
        '',
        '',
        '',
    'Hip-Hop',
    'mybeautiful.jpg',
    'https://open.spotify.com/album/20r762YmB5HeofjMCiPMLv'
),

(
    'Good Kid, M.A.A.D City', 
    'Kendrick Lamar', 
    '2012', 
    'Sherane a.k.a Master Splinters Daughter', 
    'Bitch, Dont Kill My Vibe', 
    'Backseat Freestyle', 
    'The Art of Peer Pressure', 
    'Money Trees', 
    'Poetic Justice', 
    'good kid', 
    'm.A.A.d city', 
    'Swimming Pools (Drank)', 
     '',
        '',
        '',
        '',
        '',
        '',
    'Hip-Hop',
    'goodkid.jpg',
    'https://open.spotify.com/album/3DGQ1iZ9XKUQxAUWjfC34w'
),

(
    'The Suburbs', 
    'Arcade Fire', 
    '2010', 
    'The Suburbs', 
    'Ready to Start', 
    'Modern Man', 
    'Rococo', 
    'Empty Room', 
    'City with No Children', 
    'Half Light I', 
    'Half Light II (No Celebration)', 
    'Sprawl I',
    '',
        '',
        '',
        '',
        '',
        '',
    'Indie Rock',
    'thesuburbs.jpg',
    'https://open.spotify.com/track/2UWdUez9MB9yzL7Y81Mcip'
),

(
    'Hot Fuss', 
    'The Killers', 
    '2004', 
    'Jenny Was a Friend of Mine', 
    'Mr. Brightside', 
    'Smile Like You Mean It', 
    'Somebody Told Me', 
    'All These Things That Ive Done', 
    'Midnight Show', 
    'Everything Will Be Alright', 
    'Believe Me Natalie', 
    'Dont Shoot Me Santa',
     '',
        '',
        '',
        '',
        '',
        '',
    'Indie Rock',
'hotfuss.png',
'https://open.spotify.com/album/4piJq7R3gjUOxnYs6lDCTg'
),

(
    'Blonde', 
    'Frank Ocean', 
    '2016', 
    'Nikes', 
    'Ivy', 
    'Pink + White', 
    'Be Yourself', 
    'Solo (Reprise)', 
    'Skyline To', 
    'Self Control', 
    'Good Guy', 
    'Futura Free', 
      '',
        '',
        '',
        '',
        '',
        '',
    'R&B',
    'blonde.jpg',
    'https://open.spotify.com/album/3mH6qwIy9crq0I9YQbOuDf'
),

(
    '21', 
    'Adele', 
    '2011', 
    'Rolling in the Deep', 
    'Rumour Has It', 
    'Turning Tables', 
    'Dont You Remember', 
    'Set Fire to the Rain', 
    'He Wont Go', 
    'Take It All', 
    'Ill Be Waiting', 
    'One and Only', 
    'Lovesong', 
    'Someone Like You', 
     '',
        '',
        '',
        '',
    'Pop',
   '21.png',
    'https://open.spotify.com/album/0Lg1uZvI312TPqxNWShFXL'
),

(
    'The Fame', 
    'Lady Gaga', 
    '2008', 
    'Just Dance', 
    'Lovegame', 
    'Paparazzi', 
    'Poker Face', 
    'Eh, Eh (Nothing Else I Can Say)', 
    'Beautiful, Dirty, Rich', 
    'The Fame', 
    'Money Honey', 
    'Starstruck', 
    'Boys Boys Boys', 
    'Disco Heaven',
    '',
        '',
        '',
        '',
    'Pop',
    'fame.png',
    'https://open.spotify.com/album/1jpUMnKpRlng1OJN7LJauV'
),

(
    'Blurryface', 
    'Twenty One Pilots', 
    '2015', 
    'Fairly Local', 
    'Tear in My Heart', 
    'Stressed Out', 
    'Ride', 
    'Foolish Thought', 
    'The Judge', 
    'Lane Boy', 
    'Message Man', 
    'Hometown', 
    'Not Today', 
    '',
        '',
        '',
        '',
        '',
    'Alternative',
    'blurryface.png',
    'https://open.spotify.com/album/3cQO7jp5S9qLBoIVtbkSM1'
),

(
    'Back to Black', 
    'Amy Winehouse', 
    '2006', 
    'Rehab', 
    'You Know Im No Good', 
    'Me & Mr. Jones', 
    'Just Friends', 
    'Back to Black', 
    'Love Is a Losing Game', 
    'Tears Dry on Their Own', 
    'Wake Up Alone', 
    'Some Unholy War', 
    'He Can Only Hold Her', 
     '',
        '',
        '',
        '',
        '',
    'R&B',
  'backtoblack.png',
    'https://open.spotify.com/track/30FURVTCpbKyykjSEQzGkH'
),

(
    'In the Heights (Original Broadway Cast Recording)', 
    'Lin-Manuel Miranda', 
    '2008', 
    'In the Heights', 
    'Breathe', 
    'It Wont Be Long Now', 
    'No Me Diga', 
    'Piragua', 
    'Alabanza', 
    'Blackout', 
    'The Club', 
    'Finale', 
    '',
        '',
        '',
        '',
        '',
        '',
    'Musical Theatre',
    'heights.jpg',
    'https://open.spotify.com/album/3VPHalWocJfe7VfbEW60zg'
),

(
    'The Marshall Mathers LP 2', 
    'Eminem', 
    '2013', 
    'Bad Guy', 
    'Parking Lot', 
    'Rhyme or Reason', 
    'So Far...', 
    'Survival', 
    'Legacy', 
    'Asshole', 
    'Berzerk', 
    'Rap God', 
    'Headlights', 
    '',
        '',
        '',
        '',
        '',
    'Hip-Hop',
    'marshall2.png',
    'https://open.spotify.com/album/3vOgbDjgsZBAPwV2M3bNOj'
),

(
    'Bon Iver, Bon Iver', 
    'Bon Iver', 
    '2011', 
    'Perth', 
    'Minnesota, WI', 
    'Holocene', 
    'Towers', 
    'Kamikaze', 
    'Blood Bank', 
    'Beth/Rest', 
    '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    'Folk',
    'boniver.jpg',
    'https://open.spotify.com/album/2LpfNj3vB5rOXfaawLcOBg'
),

(
    'The 20/20 Experience', 
    'Justin Timberlake', 
    '2013', 
    'Pusher Love Girl', 
    'Suit & Tie', 
    'Dont Hold the Wall', 
    'Strawberry Bubblegum', 
    'Tunnel Vision', 
    'Spaceship Coupe', 
    'That Girl', 
    'Let the Groove Get In', 
    'Mirrors', 
    'Blue Ocean Floor', 
    'Dress On',
        'Body Count',
        '',
        '',
        '',
    'Pop',
    '2020.jpg',
'https://open.spotify.com/album/0O82niJ0NpcptYRxogeEZu'
),

(
    'Life of Pablo', 
    'Kanye West', 
    '2016', 
    'Ultralight Beam', 
    'Father Stretch My Hands Pt. 1', 
    'Pt. 2', 
    'Famous', 
    'Feedback', 
    'Low Lights', 
    'Highlights', 
    'Waves', 
    'FML', 
    'Real Friends',
    '',
        '',
        '',
        '',
        '',
    'Hip-Hop',
'pablo.jpg',
'https://open.spotify.com/album/7gsWAHLeT0w7es6FofOXk1'
),

(
    'A Rush of Blood to the Head', 
    'Coldplay', 
    '2002', 
    'Politik', 
    'In My Place', 
    'God Put a Smile Upon Your Face', 
    'The Scientist', 
    'Clocks', 
    'Daylight', 
    'Green Eyes', 
    'Warning Sign', 
    'A Whisper', 
    'A Rush of Blood to the Head', 
 '',
        '',
        '',
        '',
        '',
    'Alternative',
    'rushofblood.png',
    'https://open.spotify.com/track/4JJ5zGKnb1IpERyBrfmb1y'
),

(
    'Evolve', 
    'Imagine Dragons', 
    '2017', 
    'I Dont Know Why', 
    'Whatever It Takes', 
    'Believer', 
    'Thunder', 
    'Walking the Wire', 
    'Born to Be Yours', 
    'Yesterday', 
    'Rise Up', 
    'Ill Make It Up to You',
     '',
        '',
        '',
        '',
        '',
        '',
    'Pop',
    'evolve.jpg',
    'https://open.spotify.com/album/33pt9HBdGlAbRGBHQgsZsU'
),

(
    'LP1', 
    'FKA twigs', 
    '2014', 
    'Preface', 
    'Glass & Patron', 
    'Two Weeks', 
    'Papi Pacify', 
    'Water Me', 
    'Hows That', 
    'Hours', 
    'Lights On', 
    'Kicks', 
    'FKA twigs',
      '',
        '',
        '',
        '',
        '',
    'Electronic',
    'lp1.png',
    'https://open.spotify.com/album/070rEVRV6FWywkncMWLhs6'
),

(
    'The 1975', 
    'The 1975', 
    '2013', 
    'The 1975', 
    'Love It If We Made It', 
    'Love Me', 
    'If I Believe You', 
    'Guys', 
    'Its Not Living (If Its Not With You)', 
    'Sincerity Is Scary', 
    'Mine', 
    'I Couldnt Be More in Love',
       '',
        '',
        '',
        '',
        '',
        '',
    'Alternative',
    'the1975.png',
    'https://open.spotify.com/album/33ZqJmmqFE8Z7Ak1Lxbnfb'
),

(
    'Born to Die', 
    'Lana Del Rey', 
    '2012', 
    'Born to Die', 
    'Off to the Races', 
    'Blue Jeans', 
    'Video Games', 
    'Diet Mountain Dew', 
    'National Anthem', 
    'Dark Paradise', 
    'Radio', 
    'Carmen', 
      '',
        '',
        '',
        '',
        '',
        '',
    'Pop',
    'borntodie.jpg',
    'https://open.spotify.com/album/4X8hAqIWpQyQks2yRhyqs4'
),

(
    'The Black Parade', 
    'My Chemical Romance', 
    '2006', 
    'The End.', 
    'Dead!', 
    'This Is How I Disappear', 
    'The Sharpest Lives', 
    'Welcome to the Black Parade', 
    'I Dont Love You', 
    'House of Wolves', 
    'Cancer', 
    'Mama', 
    'Sleep', 
      '',
        '',
        '',
        '',
        '',
    'Alternative',
    'blackparade.jpg',
    'https://open.spotify.com/track/5wQnmLuC1W7ATsArWACrgW'
),

(
    'Take Care', 
    'Drake', 
    '2011', 
    'Over My Dead Body', 
    'Shot for Me', 
    'Headlines', 
    'Crew Love', 
    'Take Care', 
    'Marvins Room', 
    'Under Ground Kings', 
    'Doing It Wrong', 
    'The Ride', 
    '',
        '',
        '',
        '',
        '',
        '',
    'Hip-Hop',
    'takecare.jpg',
    'https://open.spotify.com/track/124NFj84ppZ5pAxTuVQYCQ'
),

(
    'Anti', 
    'Rihanna', 
    '2016', 
    'Consideration', 
    'James Joint', 
    'Kiss It Better', 
    'Work', 
    'Desperado', 
    'Woo', 
    'Needed Me', 
    'Yeah, I Said It', 
    'Love on the Brain', 
     '',
        '',
        '',
        '',
        '',
        '',
    'R&B',
    'anti.png',
    'https://open.spotify.com/album/4UlGauD7ROb3YbVOFMgW5u'
),

(
    'Death of a Bachelor', 
    'Panic! At The Disco', 
    '2016', 
    'Victorious', 
    'Dont Threaten Me with a Good Time', 
    'Hallelujah', 
    'Emperors New Clothes', 
    'Death of a Bachelor', 
    'Crazy=Genius', 
    'LA Devotee', 
    'Golden Days', 
    'The Good, The Bad, and The Dirty',
         '',
        '',
        '',
        '',
        '',
        '',
    'Alternative',
    'deathbachelor.jpg',
    'https://open.spotify.com/track/1BECwm5qkaBwlbfo4kpYx8'
),

(
    'For Emma, Forever Ago', 
    'Bon Iver', 
    '2007', 
    'Flume', 
    'Lump Sum', 
    'Skinny Love', 
    'The Wolves (Act I and II)', 
    'Blindsided', 
    'Creature Fear', 
    'Team', 
    'For Emma', 
    'Re: Stacks',
         '',
        '',
        '',
        '',
        '',
        '',
    'Folk',
    'emma.jpg',
    'https://open.spotify.com/track/2nilAlGEZmwyaLTMMyDdLo'
),

(
    'IGOR', 
    'Tyler, The Creator', 
    '2019', 
    'IGORS THEME', 
    'EARFQUAKE', 
    'I THINK', 
    'EXACTLY WHAT YOU RUN FROM YOU END UP CHASING', 
    'RUNNING OUT OF TIME', 
    'NEW MAGIC WAND', 
    'A BOY IS A GUN*', 
    'PUPPET', 
    'WHATS GOOD', 
    'GONE, GONE / THANK YOU', 
     '',
        '',
        '',
        '',
        '',
    'Hip-Hop',
    'igor.jpg',
    'https://open.spotify.com/album/5zi7WsKlIiUXv09tbGLKsE'
),

(
    'Starboy', 
    'The Weeknd', 
    '2016', 
    'Starboy', 
    'Party Monster', 
    'False Alarm', 
    'Reminder', 
    'I Feel It Coming', 
    'Secrets', 
    'True Colors', 
    'A Lonely Night', 
    'Nothing Without You', 
      '',
        '',
        '',
        '',
        '',
        '',
    'Pop',
    'starboy.png',
    'https://open.spotify.com/track/7MXVkk9YMctZqd1Srtv4MB'
),

(
    'Melodrama', 
    'Lorde', 
    '2017', 
    'Green Light', 
    'Sober', 
    'Homemade Dynamite', 
    'The Louvre', 
    'Liability', 
    'Hard Feelings / Loveless', 
    'Sober II (Melodrama)', 
    'Writer in the Dark', 
    'Supercut', 
    'Perfect Places', 
      '',
        '',
        '',
        '',
        '',
    'Pop',
    'melodrama.png',
    'https://open.spotify.com/album/2B87zXm9bOWvAJdkJBTpzF'
),

(
    'Days Are Gone', 
    'Haim', 
    '2013', 
    'Falling', 
    'Forever', 
    'The Wire', 
    'If I could Change Your Mind',
    'Honey & I',
    'Dont Save Me', 
    'Days Are Gone',
    'My Song 5', 
    'Go Slow', 
    'Let Me Go', 
    'Running If You Call My Name', 
        '',
        '',
        '',
        '',
    'Indie Rock',
    'haim.jpg',
'https://open.spotify.com/album/729Vh0HApsm7hGDVjbmtrf'
),

(
    'From Under the Cork Tree', 
    'Fall Out Boy', 
    '2005', 
    'Irresistible', 
    'Sugar, Were Goin Down', 
    'Dance, Dance', 
    'A Little Less Sixteen Candles, a Little More "Touch Me"', 
    'Nobody Puts Baby in the Corner', 
    'Ive Got a Dark Alley and a Bad Idea That Says You Should Shut Your Mouth', 
    '7 Minutes in Heaven', 
    'Champagne for My Real Friends', 
    'Snitches and Talkers Get Stitches and Walkers', 
    '',
        '',
        '',
        '',
         '',
        '',
    'Alternative',
    'corktree.jpg',
    'https://open.spotify.com/album/5nkUSlIhtoJZMOUlB0sNCp'
),

(
    'A Moon Shaped Pool', 
    'Radiohead', 
    '2016', 
    'Bloom', 
    'Morning Mr Magpie', 
    'The Numbers', 
    'Decks Dark', 
    'Desert Island Disk', 
    'Ful Stop', 
    'Glass Eyes', 
    'Identikit', 
    'Present Tense', 
      '',
        '',
        '',
        '',
         '',
        '',
    'Alternative',
    'moonpool.jpg',
    'https://open.spotify.com/album/2ix8vWvvSp2Yo7rKMiWpkg'
),

(
    'Awaken, My Love!', 
    'Donald Glover', 
    '2016', 
    'Me and Your Mama', 
    'Have Some Love', 
    'Boogieman', 
    'Zombies', 
    'Riot', 
    'Redbone', 
    'The Night Me and Your Mama Met', 
    'Terrified', 
    'California', 
      '',
        '',
        '',
        '',
         '',
        '',
    'R&B',
    'awaken.png',
    'https://open.spotify.com/album/4JCybsNZUXWrK2Jpyn12Ni'
),

(
    'Lungs', 
    'Florence + The Machine', 
    '2009', 
    'Dog Days Are Over', 
    'Rabbit Heart (Raise It Up)', 
    'Im Not Calling You a Liar', 
    'Howl', 
    'Kiss with a Fist', 
    'Drumming Song', 
    'Between Two Lungs', 
    'My Boy Builds Coffins', 
    'Blinding', 
    '',
        '',
        '',
        '',
         '',
        '',
    'Indie Rock',
    'lungs.png',
    'https://open.spotify.com/album/6hs55qjerNNOi4ZT5bOhxV'
),

(
    'Sound & Color', 
    'Alabama Shakes', 
    '2015', 
    'Sound & Color', 
    'Dont Wanna Fight', 
    'Future People', 
    'Gimme All Your Love', 
    'Dunes', 
    'The Greatest', 
    'This Feeling', 
    'Guess Who', 
'',
        '',
        '',
        '',
         '',
        '',
        '',
    'Blues',
    'soundcolor.jpg',
    'https://open.spotify.com/track/42Z8moYh30XOVffltDDUgK'
),

(
    'The Essential Michael Jackson', 
    'Michael Jackson', 
    '2005', 
    'ABC', 
    'I Want You Back', 
    'Billie Jean', 
    'Thriller', 
    'Beat It', 
    'Bad', 
    'Smooth Criminal', 
    'Black or White', 
    'Man in the Mirror', 
      '',
        '',
        '',
         '',
        '',
        '',
    'Pop',
    'essentialmichael.jpg',
    'https://open.spotify.com/album/77dNyQA0z8dV33M4so4eRY'
),

(
    'Currents', 
    'Tame Impala', 
    '2015', 
    'Let It Happen', 
    'Nangs', 
    'The Moment', 
    'Yes Im Changing', 
    'Eventually', 
    'Gossip', 
    'The Less I Know the Better', 
    'Past Life', 
    'New Person, Same Old Mistakes', 
     '',
        '',
        '',
         '',
        '',
        '',
    'Pop',
    'currents.jpg',
    'https://open.spotify.com/album/79dL7FLiJFOO0EoehUHQBv'
),

(
    'Beyoncé', 
    'Beyoncé', 
    '2013', 
    'Pray You Catch Me', 
    'HOLD UP', 
    'Drunk in Love', 
    'Blow', 
    'No Angel', 
    'Ivy Park', 
    'Love Drought', 
    'Sandcastles', 
     '',
        '',
        '',
         '',
        '',
        '',
        '',
    'R&B',
    'beyonce.jpg',
    'https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m'
),

(
    '25', 
    'Adele', 
    '2015', 
    'Hello', 
    'Send My Love (To Your New Lover)', 
    'I Miss You', 
    'When We Were Young', 
    'Remedy', 
    'Water Under the Bridge', 
    'River Lea', 
    'Love in the Dark', 
    'Million Years Ago', 
    '',
        '',
         '',
        '',
        '',
        '',
    'Pop',
    '25.png',
    'https://open.spotify.com/album/3AvPX1B1HiFROvYjLb5Qwi'
)`;

    await client.query(SQL);
    console.log("tables created");
  } catch (err) {
    console.error("Error creating table:", err);
  }
}

app.get("/api/albums", async (req, res, next) => {
  try {
    const SQL = `
        SELECT * from albums;
      `;
    const response = await client.query(SQL);
    res.send(response.rows);
  } catch (ex) {
    next(ex);
  }
});

console.log(createTablesAndData());
createTablesAndData();

const getAlbums = async () => {
  try {
    const res = await client.query("SELECT * FROM albums");
    return res.rows;
  } catch (err) {
    console.error("Error fetching albums:", err);
    throw err;
  }
};

module.exports = { createTablesAndData, getAlbums };
